#!/bin/bash -Ee

#CONFIG=$HOME/.runbook
#LOG_FILE="$CONFIG/runbook.log"

function ps1() {
  echo -ne "\033[01;32m${USER}@$(hostname -s) \033[01;34m$(basename "$(pwd)") \$ \033[00m"
}

function echocmd() {
  echo -n "$(ps1)$@"
}

function docmd() { 
  echocmd "${@}"
  read -r
  ${@}
}

function errcmd() {
  echocmd "${@}"
  read -r
  ${@}
}

function silentcmd() {
  ${@} > /dev/null 2>&1
}

if [ $# -eq 0 ]
  then
    echo "Please specify the runbook to execute."
    exit 1
fi

echo "Starting Runbook."

trap 'echo "Runbook exited unexpectedly."' ERR

cmds=()
while read -r line; do
  cmds+=("$line")
done < "$1"

for cmd in "${cmds[@]}"
do
  case "${cmd:0:1}" in
    '~')
      (silentcmd "${cmd:1}")
      ;;
    '#')
      ;;
    '!')
      errcmd "${cmd:1}" && echo ""
      ;;
    *)
      (docmd "${cmd}")
      ;;
   esac
done

echo "Runbook Completed!"
